version: '3'
services:
  kafka-dc:
    image: wurstmeister/kafka
    container_name: kafka-mc
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
#      - KAFKA_ADVERTISED_HOST_NAME=172.30.77.78
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-dc:2181
    depends_on:
      - zookeeper-dc
  zookeeper-dc:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper-dc
